version: "3.9"
services:
  react-app:
    stdin_open: true
    tty: true
    container_name: sakura-client
    image: anhkiet/sakura-client:latest
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    networks:
      - sakura-app
    volumes:    
      - ./client:/app
      - /app/node_modules
    depends_on:
      - sakura-server
  sakura-server:
    container_name: sakura-server
    image: anhkiet/sakura-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - sakura-app
    depends_on:
      - mongodb
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - 27017:27017
    networks:
      - sakura-app
    volumes:
      - mongodb-data:/data/db
  mongo-express:
    image: mongo-express
    depends_on: 
      - mongodb
    ports: 
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123456
    volumes: 
      - mongodb-data
    networks: 
      - sakura-app
networks:
  sakura-app:
    driver: bridge
volumes:
  mongodb-data:
    driver: local
